[package]
name = "sapling"
version = "0.1.0"
authors = ["Ben White-Horne <kneasle@gmail.com>"]
edition = "2018"

[dependencies]
tuikit = "*"
typed-arena = "2.0.1"
hmap = "0.1.0"
log = "0.4.11"
pretty_env_logger = "0.4.0"
